# docker-compose.yml

version: '3.8'

services:
  nuxt-app:
    image: pulsewatch:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.data:/app/.data
