# .github/workflows/docker-publish-staging.yml

name: Build and Publish Docker Image to GHCR (Staging)

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tar: ${{ steps.save-image.outputs.image_tar }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and save as tar
        uses: docker/build-push-action@v5
        with:
          context: .
          outputs: type=docker,dest=image.tar
          tags: ghcr.io/daniel-luke/pulsewatch:staging

      - name: Upload image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download image tar artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar
          path: .

      - name: Load Docker image from tar
        run: docker load -i image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/daniel-luke/pulsewatch:staging

      - name: Log out from GHCR
        run: docker logout ghcr.io
